on:
  push:
    branches:
      - master
    
  



jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v3  

      - name: "Login to Docker hub"
        run: docker login --username ${{ secrets.DOCKER_USER }} --password dckr_pat_Lg8UvXEE8iZxt6dqAdpCRLuwyEY

      - name: "Building docker image"
        run: docker build -t ${{ secrets.DOCKER_USER }}/myimage .

      - name: "Pushing to Docker hub"
        run: docker push ${{ secrets.DOCKER_USER}}/myimage
