on:
 push :
   branches:
    - master


jobs:
  build:
   runs-on: ubuntu-latest
  steps:
    -name: 'printig folder contents before '
     run: ls
    - uses: actions/checkout@v3
    -name: 'printig folder contents after'
     run: ls


